### ISSUE TITLE
Korean Translation Progress

### ISSUE THREAD

**Issue by gatsbybot** [gatsbyjs/gatsby-ko#1]
## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide to understand how to translate various technical and Gatsby-specific terms.

Please be prompt with your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

- [ ] Home Page (@gatsbybot) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

**These pages should be translated first.** These pages must be translated to be considered an official Gatsby localization.

### Community

* [x] community/code-of-conduct (@kimdhoe) #2

### Tutorial

* [ ] tutorial/index (@kimdhoe)
* [x] tutorial/part-zero (@woonjangahn) #5 
* [x] tutorial/part-one (@idpokute)
* [x] tutorial/part-two (@idpokute)
* [x] tutorial/part-three (@idpokute)
* [ ] tutorial/part-four (@idpokute)
* [x] tutorial/part-five (@vaporwavy)
* [ ] tutorial/part-six (@jongwooo)
* [ ] tutorial/part-seven (@vaporwavy)
* [ ] tutorial/part-eight (@idpokute)
    

### Docs

* [ ] docs/index
* [x] docs/quick-start (@b6pzeusbc54tvhw5jgpyw8pwz2x6gs ) #3 
* [ ] docs/glossary (@woonjangahn)
* [ ] docs/gatsby-cli (@woonjangahn)
* [x] docs/caching (@idpokute)
* [x] docs/css-in-js(@idpokute)
* [x] docs/css-libraries-and-frameworks(@idpokute)
* [x] docs/customization(@idpokute)

    
#### Recipes

* [ ] docs/recipes  (@b6pzeusbc54tvhw5jgpyw8pwz2x6gs ) #18 
* [ ] docs/recipes/pages-layouts  (@b6pzeusbc54tvhw5jgpyw8pwz2x6gs ) #18 
* [ ] docs/recipes/styling-css  (@b6pzeusbc54tvhw5jgpyw8pwz2x6gs ) #18 
* [ ] docs/recipes/working-with-starters  (@b6pzeusbc54tvhw5jgpyw8pwz2x6gs ) #18 
* [ ] docs/recipes/working-with-themes  (@b6pzeusbc54tvhw5jgpyw8pwz2x6gs ) #18 
* [ ] docs/recipes/sourcing-data (@b6pzeusbc54tvhw5jgpyw8pwz2x6gs ) #18 
* [ ] docs/recipes/querying-data (@b6pzeusbc54tvhw5jgpyw8pwz2x6gs ) #18 
* [ ] docs/recipes/working-with-images (@b6pzeusbc54tvhw5jgpyw8pwz2x6gs ) #18 
* [ ] docs/recipes/transforming-data (@b6pzeusbc54tvhw5jgpyw8pwz2x6gs ) #18 
* [ ] docs/recipes/deploying-your-site (@b6pzeusbc54tvhw5jgpyw8pwz2x6gs ) #18 

#### API Reference

* [ ] docs/api-reference
* [ ] docs/theme-api
* [ ] docs/gatsby-link
* [ ] docs/gatsby-image (@idpokute )
* [ ] docs/gatsby-config
* [ ] docs/browser-apis
* [ ] docs/ssr-apis
* [ ] docs/api-files
* [ ] docs/api-files-gatsby-config
* [ ] docs/api-files-gatsby-browser
* [ ] docs/api-files-gatsby-node
* [ ] docs/api-files-gatsby-ssr
* [ ] docs/actions
* [ ] docs/graphql-api
* [ ] docs/node-apis
* [ ] docs/node-api-helpers
* [ ] docs/node-model
* [ ] docs/node-interface
* [ ] docs/schema-customization
* [ ] docs/api-specification

**Comment by kimdhoe** [comment]
Greetings! I'd like to start with the top one, *community/code-of-conduct*.

But before that, it would be nice if we agree on a few basic rules first, since Korean is a very different language from English. If you haven’t already, please join [Gatsby Discord](https://gatsby.dev/discord). There is a channel named _translation-ko_, where we can discuss in Korean. @b6pzeusbc54tvhw5jgpyw8pwz2x6gs @woonjangahn @idpokute

**Comment by kimdhoe** [comment]
I'll take _tutorial/index.md_.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
I'll take `docs/quick-start`

By the way I can't find the docs/index. Where is it?

**Comment by woonjangahn** [comment]
I'll take _tutorial/part_zero/index.md_.

**Comment by kimdhoe** [comment]
I don't see _docs/index_ file either. I guess it's accidentally missing and we can add it before proceeding. @tesseralis, can you clarify this?

(Edit) Thank you @tesseralis! You don't have to answer this. I just found your comment on Discord.

> I think it's because docs/index.md was only recently turned into a markdown file and I created the french repo after that
I'll make a sync script to update you ...

**Comment by kimdhoe** [comment]
@b6pzeusbc54tvhw5jgpyw8pwz2x6gs @woonjangahn Nice! You can edit this issue to add the volunteer's name next to the page title.

**Comment by idpokute** [comment]
I will take tutorial/wordpress-source-plugin-tutorial.md

**Comment by idpokute** [comment]
I will take tutorial/part-one

**Comment by woonjangahn** [comment]
I will take _docs/glossary_ and _docs/gatsby-cli_.

**Comment by idpokute** [comment]
I will take tutorial/part-two

**Comment by idpokute** [comment]
I will take tutorial/part-three

**Comment by idpokute** [comment]
I will take tutorial/part-four

**Comment by weensy** [comment]
I will take tutorial/part-five

**Comment by jongwooo** [comment]
I will take tutorial/part-six

**Comment by weensy** [comment]
I will take tutorial/part-seven

**Comment by idpokute** [comment]
I will do tutorial/part-eight.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
The **Recipes** section has been restructured, and translations are being reorganized.

**Comment by idpokute** [comment]
I will do docs/gatsby-image.
